#!/bin/bash

#Set variables to make script portable.
	path=`realpath $0`
	installdir=`dirname $path`

#Setup loop for user input.
	while true; do
	cd $installdir/youtube/
	clear

#Display input options
echo "Choose an option by entering its number located in brackets [n].
[1] Update list
[2] View list
[3] View list in spreadsheet
[4] YouTube-dl
[c] Add / Remove channels
[l] Change list layout
[q] Quit
"
	read -p "Enter an option: " ans

#Update list
if test "$ans" = "1" ;
then
	bash scripts/update
fi

#View list
if test "$ans" = "2" ;
then
cd data/

	#Setup loop for user input.
	while true; do
	clear

	#Grep for time info
	bash options2

	#Organize layout by time.
	bash options3

	#Build list
	bash options4
	cat list timestamp

	#Display input options
echo "
Choose an option by entering it's number located in brackets [n]
[l] Change list layout
[i] Display video info
[b] Go Back
"
	read -p "Enter an option: " ans2

	#Change list layout
	if test "$ans2" = "l" ;
	then
		cd data/
		nano options3
	fi

	#Display video info
	if test "$ans2" = "i" ;
	then
		read -p "Input the number of a URL from the list:	" ans
		clear
		URL=$(grep 'URL' vidl_URL2 | rev | cut -d "=" -f1 | rev | sed "$ans q;d" | sed 's|^|https://www.youtube.com/watch?v=|') &&
		cd ../store &&
		wget -O $ans-info_file $URL &&
		clear
		echo "[$ans-URL]" > ../data/$ans-info_file
		grep -m1 /title $ans-info_file | sed 's|<title>|[Title: |g' | sed 's|</title>.*||g' | sed 's|- YouTube|]\n|g' | sed 's/%21/!/g' | sed 's/%3A/:/g' | sed 's/%3F/?/g' | sed 's/%3D/=/g'| sed 's/%26/\&/g' | sed 's/\&quot;/"/g' | sed 's/\&amp;/\&/g' | sed "s/\&#39;/'/g" >> ../data/$ans-info_file
		grep "eow-description" $ans-info_file | sed 's|.*eow-description" class="" >||g' | sed 's|</div>  <div id="watch-description-extras">||g' | sed 's|<br />|\n|g' | sed 's|%21|!|g' | sed 's|%3A|:|g' | sed 's|%3F|?|g' | sed 's|%3D|=|g'| sed 's|%26|\&|g' | sed 's|</a>||g' | sed 's|</p>||g' | sed 's|%2F|/|g' | sed 's|nofollow.*||g' | sed 's|" data-sessionlink.*...||g'| sed s'|<a href.*https|https|g' | sed s'|<a href.*http|http|g' | sed 's|&amp.*||g' | sed 's|" class.*||g' | sed 's|" target.*||g' | sed 's|" rel.*||g' | sed s'|<a href.*false;">||g' >> ../data/$ans-info_file
		cat ../data/$ans-info_file
		read -s -n 1 -p "Press any key to continue..."
		rm $ans-info_file ../data/$ans-info_file
		cd ../data
	fi

	#Go Back
	if test "$ans2" = "b" ;
	then
		break
	fi
	done
fi

#View list in spread sheet.
if test "$ans" = "3" ;
then
cd data/
	#Grep for time info
	bash options2

	#Organize layout by time.
	bash options3

	#Build list
	bash options4
	localc list.ods
fi

#YouTube-dl
if test "$ans" = "4" ;
then
	bash scripts/vidl
fi

#Add / Remove channels
if test "$ans" = "c" ;
then
	nano channels
fi

#Change list layout
if test "$ans" = "l" ;
then
	nano data/options3
fi

#Quit
if test "$ans" = "q" ;
then
	clear
	exit
fi
done

